### ISSUE TITLE
"OpenShift” is hidden in the image

### ISSUE THREAD

**Issue by ssetoredhat** [rh-mad-workshop/mad-dev-guides-m7#6]
![image](https://github.com/rh-mad-workshop/mad-dev-guides-m7/assets/100739386/9848a494-7ade-44ac-bf1f-154a640f6186)

Top of this image.
https://github.com/rh-mad-workshop/mad-dev-guides-m7/blob/patch-postgres/documentation/modules/ROOT/assets/images/intro/rhdh_architecture.png

**Comment by danieloh30** [comment]
@hguerrero @varodrig Can you update the logo?

**Comment by hguerrero** [comment]
@varodrig if you can send me the source for the image I can update it.

**Comment by varodrig** [comment]
I'll send you on a DM

**Comment by hguerrero** [comment]
@danieloh30 @varodrig you can merge the PR or give me write rights to do it.

**Comment by danieloh30** [comment]
Merged. Thanks for fixing this.
